version: '3.3'
services:

  mysqldb:
    container_name: "database-container"
    image: denispasha/mysql-db:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 125963Denis
      MYSQL_DATABASE: hikeAddicts


  mail:
    container_name: "my-mailhog"
    image: denispasha/mailhog:latest
    ports:
      - "1025:1025"
      - "8090:8025"


  hikeAddictApp:
    build: .
    image: denispasha/hike-addicts:v1
    container_name: hikeAddictApp
    depends_on:
      - mail
      - mysqldb
    ports:
      - "8080:8080" # web ui
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-container:3306/hikeAddicts
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 125963Denis







