global:
  scrape_interval: 10s
  evaluation_interval: 20s

scrape_configs:
  - job_name: rest-service
    honor_labels: true

    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']